name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:27

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: make
    - name: Proper tests
      run: make proper && make proper
    - name: Common tests
      run: make ct
    - name: Dialyzer
      run: make dialyze
